---
correct:
  custom_server_cert: |
    -----BEGIN CERTIFICATE-----
    MIIDxzCCAq8CFELj6xaTPD+SRVzR1h1gTOAgF5RGMA0GCSqGSIb3DQEBDQUAMIGf
    MQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNTW91
    bnRhaW4gVmlldzEQMA4GA1UECgwHV29ya2F0bzEPMA0GA1UECwwGRGV2b3BzMR0w
    GwYDVQQDDBRUZXN0IFJvb3QgU2VydmVycyBDQTEhMB8GCSqGSIb3DQEJARYSZGV2
    b3BzQHdvcmthdG8uY29tMB4XDTIwMDQwMjAwMzU1OVoXDTMwMDMzMTAwMzU1OVow
    gZ8xCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1N
    b3VudGFpbiBWaWV3MRAwDgYDVQQKDAdXb3JrYXRvMQ8wDQYDVQQLDAZEZXZvcHMx
    HTAbBgNVBAMMFFRlc3QgUm9vdCBTZXJ2ZXJzIENBMSEwHwYJKoZIhvcNAQkBFhJk
    ZXZvcHNAd29ya2F0by5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
    AQDEdEzr3QasXorEL+BikGRF05K8fSbq6SVIh1tsEY0et0IRJJdcmrGvO+J6+k6y
    A+B3csAAj07XLNUYJbxRh4imMS2r1pKoBNrGPfa6rGygHKfTPXV8sSxPEYpp4m+O
    Z9oVakPbCK4v8mRCm4+x+1e0Isy7tAUhHqQDJ7efJMNM4keFyhPzFG4CvEA6SXEF
    fUWUO6kL6K51Wi2xQQEMyxAeinzt+EXe4W3E+Il70ewjBT0yuQVhU3K25Rn4u4K7
    F6CxPoUybAm52hZRMtVEG0Hsb+T3dbxh3G8T1j12kkUwsqXLQhU946iq5YL4WCnO
    oDXUxGkg248PzkwVZZgnvtJZAgMBAAEwDQYJKoZIhvcNAQENBQADggEBAIKTAbki
    jb2KPPS9X4Vs/BRzxWPmekmxBlwWH75NTpQecL8Hj1TOwsX+Mso1Mn1G/aSoq9Uu
    lBV4ETaxTltbbZKKwBKluRgjzk6plsgNCwZo8YJmn/bsZnFM1oJ/8BqPNgQVVefh
    CzlWvHFETZLLi77CSqmEHElwrdLjI1sfmA1AXb+YPJjhcQyr8Pi8FnvJpvekQxVL
    O48My6VNotBurhTXzmWkmtY4ogepPuJUA+utJPtTraCQoKnsE+uHv5tmQO1zVm12
    GUGe2XGtoXDmcf1UCVpZS6fckfkRVmoOYaTWkG4LIuugvZr07pu+tcJOXlds8QmV
    1xXCSzvBvtRZYAU=
    -----END CERTIFICATE-----
wrong:
  custom_server_cert: |
    -----BEGIN CERTIFICATE-----
    MIIDxzCCAq8CFGbE1agzDA7M06aItx19eRDiVGARMA0GCSqGSIb3DQEBDQUAMIGf
    MQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNTW91
    bnRhaW4gVmlldzEQMA4GA1UECgwHV29ya2F0bzEPMA0GA1UECwwGRGV2b3BzMR0w
    GwYDVQQDDBRUZXN0IFJvb3QgQ2xpZW50cyBDQTEhMB8GCSqGSIb3DQEJARYSZGV2
    b3BzQHdvcmthdG8uY29tMB4XDTIwMDQwMjAwMzYzMFoXDTMwMDMzMTAwMzYzMFow
    gZ8xCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1N
    b3VudGFpbiBWaWV3MRAwDgYDVQQKDAdXb3JrYXRvMQ8wDQYDVQQLDAZEZXZvcHMx
    HTAbBgNVBAMMFFRlc3QgUm9vdCBDbGllbnRzIENBMSEwHwYJKoZIhvcNAQkBFhJk
    ZXZvcHNAd29ya2F0by5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
    AQCpWbMC7qOED9iYSpAURFbJ5HIQ0P5wA2FWWfwZg26vx6OpfBSwSunXp8G7MydM
    Z2EWhArmXN/BVPPRjbEXEzxh5cHOlJTooISeyP+JHbXeCpz0AFFC+TApCxTGrR6g
    trHEtpG/FF6m5HButGJGesqMeSdof9VXWJv2tEbaNU1E3tCdKlRx7HmaAljGY/Ze
    AaCKEVlxQPT/9iAB4HsHh28OfnOnzKXMqHlFQrpRl110Amako+WXAPcG8//hCcZr
    NQNC1Gpt0v7BdzsQMqSQSP6abD4tuS8+q1iE8eWoweX/Y7SKPy3Sx8HsXlW29hfh
    J3wQsIHsFMxVJmKLt3bEX1pnAgMBAAEwDQYJKoZIhvcNAQENBQADggEBAEEazlbh
    4PM4mThdbCk8KjWTytUnNTeyd71uW8P903f3WObEz6QjEb33++nIIlzpFdcl9pxC
    9yy+K3IFIanETo25a3/BouyAnIw3daC5OHytx62k8WDsj9/Zzt1+dbLE6VhOiyX2
    eFqiN9DPo2pXYkr3LnbgCbWejq8iVaHH5IsMdmY3cJYLJ90hIwM0kiKDdpmyvLrb
    EEMC9vKLrEcdR5fWUVYob56seU2HRwnwAl005EN9FhKzUINRCDdOUOgP1QJTeupN
    Ne78iJiM0Eew2A7K5EnZWexX77hwo2qk0UmDvR+PV4SCPt7pW8bnZKvqRsmVMxtX
    t0276brpqJxOQKU=
    -----END CERTIFICATE-----